name: Release Nightly

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js v16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: NPM Install
      run: cd src; npm i; cd ..

    - name: Install Asar
      run: npm i -g asar

    - name: Pack Asar
      run: npx asar pack src openasar.asar

    - name: Make Deps Asar
      run: |
        cd src
        npm install request
        cd ..
        npx asar pack src openasar-with-deps.asar

    - name: GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: "nightly"
        allowUpdates: true
        prerelease: true
        artifacts: "app.asar,openasar-with-deps.asar"

        name: "Nightly"

        token: ${{ secrets.GITHUB_TOKEN }}