name: Release Nightly

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js v16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: NPM Install
      run: cd src; npm i; cd ..

    - name: Pack
      run: |
        npm i -g asar
        node injectPolyfills.js
        rm -rf src/package-lock.json src/node_modules/.package-lock.json src/splash/splashScreen.js.self
        npx asar pack src openasar.asar

    - name: GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: "nightly"
        allowUpdates: true
        prerelease: true
        artifacts: "openasar.asar"

        name: "Nightly"

        token: ${{ secrets.GITHUB_TOKEN }}